#lang racket

;; 1.2
;; The ability to visualize the consequences of the actions under consideration
;; is crucial to becoming an expert programmer.
;; To become experts, we must learn to visualize the processes generated by
;; various type of procedures.
;; Only after we have developed such a skill can we learn to reliably
;; construct programs that exhibit the desired behaviour.

